name: Code quality

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - main
    workflow_call:

concurrency:
    group: code-quality-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    code-quality:
        name: Code quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Install
              run: pnpm i

            - name: Code quality
              run: pnpm run check

            - name: Build
              run: pnpm run build
