name: Release please

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
              id: release
              with:
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
                  config-file: release-please-config.json
                  manifest-file: release-please-manifest.json

            - name: Print release outputs for debugging
              continue-on-error: true
              run: |
                  echo '${{ toJson(steps.release.outputs) }}' | jq .
